<a href="https://colab.research.google.com/github/monrafa/Datos-Colab/blob/master/ML_19_C1_colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

>[Tutorial Google Colab](#scrollTo=_HVNgIPHRJdi)

# <h1>Tutorial Google Colab</h1>
Colaboratory es un entorno gratuito de Jupyter Notebook que no requiere configuración y que se ejecuta completamente en la nube.

Colaboratory permite escribir y ejecutar código, guardar y compartir tus análisis y tener acceso a recursos informáticos muy potentes, todo de forma gratuita desde el navegador.


> Todos los cuadernos de Colaboratory se almacenan en Google Drive. Estos se pueden compartir de la misma manera que las Hojas de cálculo o los Documentos de Google. Simplemente haz clic en el botón para compartir que aparece en la parte superior derecha de los cuadernos de Colaboratory o sigue estas instrucciones para compartir archivos en Google Drive.

> Si eliges compartir un cuaderno, se comparte todo su contenido (texto, código y resultado). Para impedir que se guarde o comparta el resultado de la celda de código, selecciona Editar > Configuración del cuaderno > Omitir el resultado de la celda al guardar este cuaderno. De este modo, no se compartirá la máquina virtual que estés usando, incluidos los archivos y las bibliotecas personalizados que hayas configurado. Por lo tanto, es buena idea incluir celdas que instalen y carguen todas las [bibliotecas](https://colab.research.google.com/notebooks/snippets/importing_libraries.ipynb) o los [archivos](https://colab.research.google.com/notebooks/io.ipynb) personalizados que necesite tu cuaderno.

> Todos los cuadernos de Colaboratory se almacenan en el formato de cuaderno de Jupyter de código abierto (.ipynb).
Para descargar los cuadernos de Colaboratory que hayas creado en Google Drive,  accede al menú "Archivo" de Colaboratory.

> Una opción bastante interesante de Colab es la posibilidad de guardar y fijar revisiones de los cuadernos, restaurarlos e incluso descargarlos. Desde el menú "Archivo"

## Como montar una unidad de Drive compartida
Primero montamos la unidad de Drive (asociada al usuario de Google)
Desde ahí podremos utilizar archivos "compartidos" de datos para todos nuestros ejemplos de código

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

In [14]:
!ls "/content/gdrive/My Drive/Colab Notebooks/ML_Colab/data"

insurance.csv

In [12]:
import pandas as pd
pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/ML_Colab/data/insurance.csv')

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
5      31  female  25.740         0     no  southeast   3756.62160
6      46  female  33.440         1     no  southeast   8240.58960
7      37  female  27.740         3     no  northwest   7281.50560
8      37    male  29.830         2     no  northeast   6406.41070
9      60  female  25.840         0     no  northwest  28923.13692
10     25    male  26.220         0     no  northeast   2721.32080
11     62  female  26.290         0    yes  southeast  27808.72510
12     23    male  34.400         0     no  southwest   1826.84300
13     56  female  39.820         0     no  southeast  11090.71780
14     27    male  42.130         0    yes  southeast  39611.75770
15     19    male  24.600         1     no  southwest   1837.23700
16     52  female  30.780         1     no  northeast  10797.33620
17     23    male  23.845         0     no  northeast   2395.17155
18     56    male  40.300         0     no  southwest  10602.38500
19     30    male  35.300         0    yes  southwest  36837.46700
20     60  female  36.005         0     no  northeast  13228.84695
21     30  female  32.400         1     no  southwest   4149.73600
22     18    male  34.100         0     no  southeast   1137.01100
23     34  female  31.920         1    yes  northeast  37701.87680
24     37    male  28.025         2     no  northwest   6203.90175
25     59  female  27.720         3     no  southeast  14001.13380
26     63  female  23.085         0     no  northeast  14451.83515
27     55  female  32.775         2     no  northwest  12268.63225
28     23    male  17.385         1     no  northwest   2775.19215
29     31    male  36.300         2    yes  southwest  38711.00000
...   ...     ...     ...       ...    ...        ...          ...
1308   25  female  30.200         0    yes  southwest  33900.65300
1309   41    male  32.200         2     no  southwest   6875.96100
1310   42    male  26.315         1     no  northwest   6940.90985
1311   33  female  26.695         0     no  northwest   4571.41305
1312   34    male  42.900         1     no  southwest   4536.25900
1313   19  female  34.700         2    yes  southwest  36397.57600
1314   30  female  23.655         3    yes  northwest  18765.87545
1315   18    male  28.310         1     no  northeast  11272.33139
1316   19  female  20.600         0     no  southwest   1731.67700
1317   18    male  53.130         0     no  southeast   1163.46270
1318   35    male  39.710         4     no  northeast  19496.71917
1319   39  female  26.315         2     no  northwest   7201.70085
1320   31    male  31.065         3     no  northwest   5425.02335
1321   62    male  26.695         0    yes  northeast  28101.33305
1322   62    male  38.830         0     no  southeast  12981.34570
1323   42  female  40.370         2    yes  southeast  43896.37630
1324   31    male  25.935         1     no  northwest   4239.89265
1325   61    male  33.535         0     no  northeast  13143.33665
1326   42  female  32.870         0     no  northeast   7050.02130
1327   51    male  30.030         1     no  southeast   9377.90470
1328   23  female  24.225         2     no  northeast  22395.74424
1329   52    male  38.600         2     no  southwest  10325.20600
1330   57  female  25.740         2     no  southeast  12629.16560
1331   23  female  33.400         0     no  southwest  10795.93733
1332   52  female  44.700         3     no  southwest  11411.68500
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

## Utilizar ficheros en local

Subir ficheros desde el sistema local

In [15]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving Desert.jpg to Desert.jpg
User uploaded file "Desert.jpg" with length 845941 bytes

Descargar ficheros en sistema local

In [0]:
from google.colab import files

with open('ejemplo.txt', 'w') as f:
  f.write('contenido de prueba')

files.download('ejemplo.txt')